version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123456       # root 密码
      MYSQL_DATABASE: xingoa                 # 初始数据库
      MYSQL_USER: user123                   # 自定义用户
      MYSQL_PASSWORD: pass123               # 自定义用户密码
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
